#!/bin/ksh

echo "Content-type: text/html"
echo
echo


echo "$(< /dev/stdin)&$QUERY_STRING" | tr '&' '\n' | while read -r kv
do
    if [[ -n "$kv" ]]
    then
	export "PARAM_$kv"
    fi
done

(echo '

cd '"$(dirname "$SCRIPT_FILENAME")"'

export PATH=".:$PATH"

wsh_urldecode()
{
  string_to_decode="$(sed '"'"'s/%\(..\)/\\x\1/g;'"'"')"
  echo a | sed s/a/"$string_to_decode"/ | sed "s/+/ /g"
}

wsh_input()
{
   eval "echo \$PARAM_$1"
}

' ; sed 1d "$SCRIPT_FILENAME" | tr '\n' '霞' | sed -e s/'<?wsh'/'\x0A<?wsh'/g  -e s/'?>'/'?>\x0A'/g | sed -e s/"'"/"'\"'\"'"/g -e s/'^'/"echo -n '"/g -e s/'$'/"'"/g -e s/"^echo -n '<?wsh"//g -e s/"?>'$"//g | tr '霞' '\n') | ksh
